Repository openstack-k8s-operators/openstack-operator, pull requests merged in 2022-10, with the labels that each got.

#28 Add storageClass to sample CR's Glance template
  config/samples/core_v1beta1_openstackcontrolplane.yaml
Labels: approved, lgtm

#24 Add Cinder to ControlPlane CR
  apis/core/v1beta1/openstackcontrolplane_types.go
  apis/core/v1beta1/zz_generated.deepcopy.go
  apis/go.mod
  apis/go.sum
  config/crd/bases/core.openstack.org_openstackcontrolplanes.yaml
  config/rbac/role.yaml
  config/samples/core_v1beta1_openstackcontrolplane.yaml
  controllers/core/openstackcontrolplane_controller.go
  custom-bundle.Dockerfile
  go.mod
  go.sum
  main.go
  pkg/openstack/cinder.go
Labels: approved

#35 Add status conditions
  apis/core/v1beta1/conditions.go
  apis/core/v1beta1/openstackcontrolplane_types.go
  apis/core/v1beta1/zz_generated.deepcopy.go
  apis/go.mod
  apis/go.sum
  config/crd/bases/core.openstack.org_openstackcontrolplanes.yaml
  controllers/core/openstackcontrolplane_controller.go
  go.mod
  go.sum
  pkg/openstack/cinder.go
  pkg/openstack/glance.go
  pkg/openstack/keystone.go
  pkg/openstack/mariadb.go
  pkg/openstack/placement.go
  pkg/openstack/rabbitmq.go
Labels: approved, lgtm

#36 Use ISO8601 time encoding for logging
  main.go
Labels: approved, lgtm, ok-to-test
