Repository openstack-k8s-operators/openstack-operator, pull requests merged in 2022-11, with the labels that each got.

#27 Rabbitmq TransportURL CR support
  PROJECT
  apis/rabbitmq/v1beta1/conditions.go
  apis/rabbitmq/v1beta1/groupversion_info.go
  apis/rabbitmq/v1beta1/transporturl_types.go
  apis/rabbitmq/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/rabbitmq.openstack.org_transporturls.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_rabbitmq_transporturls.yaml
  config/crd/patches/webhook_in_rabbitmq_transporturls.yaml
  config/manifests/bases/openstack-operator.clusterserviceversion.yaml
  config/rbac/rabbitmq_transporturl_editor_role.yaml
  config/rbac/rabbitmq_transporturl_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/rabbitmq_v1beta1_transporturl.yaml
  controllers/rabbitmq/suite_test.go
  controllers/rabbitmq/transporturl_controller.go
  main.go
  pkg/rabbitmq/funcs.go
Labels: approved, lgtm

#37 Use OSP17 RabbitMQ image by default instead of the upstream one
  pkg/openstack/rabbitmq.go
Labels: approved, lgtm, ok-to-test

#44 Lint improvements
  .github/workflows/golangci-lint.yaml
  .gitignore
  Makefile
  apis/core/v1beta1/openstackcontrolplane_types.go
  config/crd/bases/core.openstack.org_openstackcontrolplanes.yaml
Labels: approved, lgtm

#45 Update to the latest glance api modules
  apis/go.mod
  apis/go.sum
  config/crd/bases/core.openstack.org_openstackcontrolplanes.yaml
  go.mod
  go.sum
Labels: approved, lgtm

#47 Bump glance-operator/api version
  config/crd/bases/core.openstack.org_openstackcontrolplanes.yaml
  config/samples/core_v1beta1_openstackcontrolplane.yaml
  go.mod
  go.sum
Labels: approved, lgtm

#48 Bump glance-operator in apis/go.mod
  apis/go.mod
  apis/go.sum
Labels: approved, lgtm

#49 Add /apis directory to dependabot
  .github/dependabot.yml
Labels: approved, lgtm

#54 Update config sample for new format (service subset deployment)
  config/samples/core_v1beta1_openstackcontrolplane.yaml
Labels: approved, lgtm

#56 Fix invalid: metadata.annotations: Too long
  Makefile
Labels: approved, lgtm, ok-to-test

#66 Update github.com/openstack-k8s-operators/glance-operator/api digest …
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
Labels: approved

#74 Use crd:maxDescLen=0 only when required
  Makefile
Labels: approved, lgtm

#73 Update crd with latest keystone/placement updates
  apis/bases/core.openstack.org_openstackcontrolplanes.yaml
  config/crd/bases/core.openstack.org_openstackcontrolplanes.yaml
  config/samples/core_v1beta1_openstackcontrolplane.yaml
Labels: approved, lgtm

#77 update container images to stable zed
  config/samples/core_v1beta1_openstackcontrolplane.yaml
Labels: approved, lgtm

#81 Update github.com/openstack-k8s-operators/glance-operator/api digest …
  apis/bases/core.openstack.org_openstackcontrolplanes.yaml
  apis/go.mod
  apis/go.sum
  config/crd/bases/core.openstack.org_openstackcontrolplanes.yaml
  go.mod
  go.sum
Labels: approved, lgtm

#82 Pre commit
  .pre-commit-config.yaml
  README.md
  custom-bundle.Dockerfile
  go.sum
  hack/boilerplate.go.txt
Labels: approved, lgtm

#84 Add container for CI testing binaries (pre-commit)
  containers/ci/Dockerfile
Labels: approved

#85 fix maxDescLen for deploy target
  Makefile
Labels: approved, lgtm

#86 Disable golangci in .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: approved, lgtm

#75 Add OVN DBCluster and Northd to ControlPlane CR
  apis/bases/core.openstack.org_openstackcontrolplanes.yaml
  apis/core/v1beta1/conditions.go
  apis/core/v1beta1/openstackcontrolplane_types.go
  apis/core/v1beta1/zz_generated.deepcopy.go
  apis/go.mod
  apis/go.sum
  config/crd/bases/core.openstack.org_openstackcontrolplanes.yaml
  config/rbac/role.yaml
  config/samples/core_v1beta1_openstackcontrolplane.yaml
  controllers/core/openstackcontrolplane_controller.go
  custom-bundle.Dockerfile
  go.mod
  go.sum
  main.go
  pkg/openstack/ovn.go
Labels: approved, lgtm

#90 Bump to python 3.9 for CI Dockerfile
  containers/ci/Dockerfile
Labels: approved, lgtm

#91 pre-commit fixes
  .github/create_bundle.sh
  .github/create_opm_index.sh
  .pre-commit-config.yaml
  config/samples/core_v1beta1_openstackcontrolplane.yaml
Labels: approved, lgtm
