Repository openstack-k8s-operators/openstack-operator, pull requests merged in 2023-05, with the labels that each got.

#288 [sample][memcached]Remove unnecessary defaults
  config/samples/core_v1beta1_openstackcontrolplane.yaml
  config/samples/core_v1beta1_openstackcontrolplane_collapsed_cell.yaml
  config/samples/core_v1beta1_openstackcontrolplane_galera.yaml
  config/samples/core_v1beta1_openstackcontrolplane_galera_3replicas.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation_ceph.yaml
Labels: approved, lgtm

#292 Add container image default for ironic-neutron-agent
  apis/bases/core.openstack.org_openstackcontrolplanes.yaml
  apis/go.mod
  apis/go.sum
  config/crd/bases/core.openstack.org_openstackcontrolplanes.yaml
  go.mod
  go.sum
  main.go
Labels: approved, lgtm

#298 Drop containerImages from samples
  config/samples/core_v1beta1_openstackcontrolplane.yaml
  config/samples/core_v1beta1_openstackcontrolplane_collapsed_cell.yaml
  config/samples/core_v1beta1_openstackcontrolplane_galera.yaml
  config/samples/core_v1beta1_openstackcontrolplane_galera_3replicas.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation_ceph.yaml
Labels: approved, lgtm

#232 Replace TripleO images by TCIB images
  Makefile
  config/default/manager_default_images.yaml
Labels: approved, lgtm

#301 Refine ironic template in config samples
  config/samples/core_v1beta1_openstackcontrolplane.yaml
  config/samples/core_v1beta1_openstackcontrolplane_collapsed_cell.yaml
  config/samples/core_v1beta1_openstackcontrolplane_galera.yaml
  config/samples/core_v1beta1_openstackcontrolplane_galera_3replicas.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation_ceph.yaml
Labels: approved, lgtm

#302 Bump horizon-operator
  apis/bases/core.openstack.org_openstackcontrolplanes.yaml
  apis/core/v1beta1/openstackcontrolplane_types.go
  apis/go.mod
  apis/go.sum
  config/crd/bases/core.openstack.org_openstackcontrolplanes.yaml
  controllers/core/openstackcontrolplane_controller.go
  go.mod
  go.sum
  main.go
  pkg/openstack/horizon.go
Labels: approved, lgtm

#303 Bump dataplane-operator
  go.mod
  go.sum
Labels: approved, lgtm

#308 Move ironic template defaulting to the webhook
  apis/core/v1beta1/openstackcontrolplane_webhook.go
  pkg/openstack/ironic.go
Labels: approved, lgtm

#307 github workflowupdates for master to main update
  .github/workflows/build-openstack-operator.yaml
Labels: approved

#314 Allow 'internal' Nova webhooks to remain enabled
  cmd/csv-merger/csv-merger.go
Labels: approved, lgtm

#317 Integrate dns into ctlplane
  apis/bases/core.openstack.org_openstackcontrolplanes.yaml
  apis/core/v1beta1/conditions.go
  apis/core/v1beta1/openstackcontrolplane_types.go
  apis/core/v1beta1/openstackcontrolplane_webhook.go
  apis/core/v1beta1/zz_generated.deepcopy.go
  apis/go.mod
  apis/go.sum
  config/crd/bases/core.openstack.org_openstackcontrolplanes.yaml
  config/rbac/role.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation_ceph.yaml
  controllers/core/openstackcontrolplane_controller.go
  go.mod
  go.sum
  main.go
  pkg/openstack/dnsmasq.go
  pkg/openstack/rabbitmq.go
Labels: approved, lgtm

#312 fix local registry support for PRs
  hack/pin-custom-bundle-dockerfile.sh
Labels: approved, lgtm

#309 Telemetry operator
  apis/bases/core.openstack.org_openstackcontrolplanes.yaml
  apis/core/v1beta1/conditions.go
  apis/core/v1beta1/openstackcontrolplane_types.go
  apis/core/v1beta1/openstackcontrolplane_webhook.go
  apis/core/v1beta1/zz_generated.deepcopy.go
  apis/go.mod
  apis/go.sum
  cmd/csv-merger/csv-merger.go
  config/crd/bases/core.openstack.org_openstackcontrolplanes.yaml
  config/manifests/bases/openstack-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/samples/core_v1beta1_openstackcontrolplane.yaml
  config/samples/core_v1beta1_openstackcontrolplane_collapsed_cell.yaml
  config/samples/core_v1beta1_openstackcontrolplane_galera.yaml
  config/samples/core_v1beta1_openstackcontrolplane_galera_3replicas.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation_ceph.yaml
  controllers/core/openstackcontrolplane_controller.go
  custom-bundle.Dockerfile
  go.mod
  go.sum
  main.go
  pkg/openstack/telemetry.go
Labels: approved, lgtm, ok-to-test

#324 Move rabbit into its own bundle
  .github/create_opm_index.sh
  custom-bundle.Dockerfile
  dependencies.yaml
Labels: approved, lgtm

#325 update openstack-k8s-operators
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
Labels: approved, lgtm

#315 Migrate to OVNController from ovn-operator
  apis/bases/core.openstack.org_openstackcontrolplanes.yaml
  apis/core/v1beta1/conditions.go
  apis/core/v1beta1/openstackcontrolplane_types.go
  apis/core/v1beta1/openstackcontrolplane_webhook.go
  apis/core/v1beta1/zz_generated.deepcopy.go
  apis/go.mod
  apis/go.sum
  cmd/csv-merger/csv-merger.go
  config/crd/bases/core.openstack.org_openstackcontrolplanes.yaml
  config/rbac/role.yaml
  config/samples/core_v1beta1_openstackcontrolplane.yaml
  config/samples/core_v1beta1_openstackcontrolplane_collapsed_cell.yaml
  config/samples/core_v1beta1_openstackcontrolplane_galera.yaml
  config/samples/core_v1beta1_openstackcontrolplane_galera_3replicas.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation_ceph.yaml
  controllers/core/openstackcontrolplane_controller.go
  custom-bundle.Dockerfile
  go.mod
  go.sum
  main.go
  pkg/openstack/ovn.go
  pkg/openstack/ovs.go
Labels: approved, lgtm
