Repository openstack-k8s-operators/openstack-operator, pull requests merged in 2024-04, with the labels that each got.

#722 Add Neutron's default route annotations
  apis/core/v1beta1/openstackcontrolplane_webhook.go
  tests/functional/openstackoperator_controller_test.go
Labels: lgtm, ok-to-test

#728 Fix TLS custom CA for rabbitmq and nova
  pkg/openstack/common.go
  pkg/openstack/nova.go
  pkg/openstack/rabbitmq.go
Labels: approved, lgtm

#710 [tlse] TLS for telemetry ceilometer, metricstorage
  apis/bases/core.openstack.org_openstackcontrolplanes.yaml
  apis/core/v1beta1/openstackcontrolplane_types.go
  apis/core/v1beta1/zz_generated.deepcopy.go
  apis/go.mod
  apis/go.sum
  config/crd/bases/core.openstack.org_openstackcontrolplanes.yaml
  config/rbac/role.yaml
  controllers/client/openstackclient_controller.go
  go.mod
  go.sum
  pkg/openstack/telemetry.go
  pkg/openstackclient/funcs.go
Labels: approved, lgtm

#727 Enable TLS-e by default
  apis/bases/core.openstack.org_openstackcontrolplanes.yaml
  apis/core/v1beta1/openstackcontrolplane_types.go
  apis/go.mod
  apis/go.sum
  config/crd/bases/core.openstack.org_openstackcontrolplanes.yaml
  go.mod
  go.sum
  tests/kuttl/common/assert-sample-deployment.yaml
  tests/kuttl/tests/collapsed/01-assert-collapsed-cell.yaml
  tests/kuttl/tests/galera-3replicas/01-assert-galera-3replicas.yaml
  tests/kuttl/tests/galera-basic/01-assert-galera.yaml
Labels: approved, lgtm

#734 [tls] fix status.tls.caList[].expires
  pkg/openstack/ca.go
Labels: approved, lgtm

#743 [tls] add tls for public endpoint sample
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation_tls_public_endpoint.yaml
Labels: approved, lgtm

#742 Switch to tempest role for running tempest
  zuul.d/projects.yaml
Labels: approved, lgtm

#740 [tls] add the fqdn containing the cluster.local to the service certs
  pkg/openstack/common.go
  pkg/openstack/galera.go
  pkg/openstack/memcached.go
  pkg/openstack/rabbitmq.go
  pkg/openstack/redis.go
Labels: approved, lgtm

#747 Bump dataplane-operator
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
Labels: approved, lgtm

#749 OpenstackVersion: add save conditions logic
  controllers/core/openstackversion_controller.go
Labels: approved, lgtm

#741 Add multipathd image and Fix EDPM $RELATED_IMAGE* vars for consistency
  apis/bases/core.openstack.org_openstackcontrolplanes.yaml
  apis/bases/core.openstack.org_openstackversions.yaml
  apis/core/v1beta1/openstackversion_types.go
  apis/core/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/core.openstack.org_openstackcontrolplanes.yaml
  config/crd/bases/core.openstack.org_openstackversions.yaml
  hack/export_related_images.sh
  pkg/openstack/version.go
  tests/functional/openstackversion_controller_test.go
Labels: approved, lgtm

#739 [tls] set organization on galera certificate
  pkg/openstack/galera.go
Labels: approved, lgtm

#751 ObservedGeneration and condition save updates
  apis/bases/client.openstack.org_openstackclients.yaml
  apis/bases/core.openstack.org_openstackcontrolplanes.yaml
  apis/bases/core.openstack.org_openstackversions.yaml
  apis/client/v1beta1/openstackclient_types.go
  apis/core/v1beta1/openstackcontrolplane_types.go
  apis/core/v1beta1/openstackversion_types.go
  config/crd/bases/client.openstack.org_openstackclients.yaml
  config/crd/bases/core.openstack.org_openstackcontrolplanes.yaml
  config/crd/bases/core.openstack.org_openstackversions.yaml
  controllers/client/openstackclient_controller.go
  controllers/core/openstackcontrolplane_controller.go
  controllers/core/openstackversion_controller.go
Labels: approved, lgtm

#748 Remove redis
  apis/bases/core.openstack.org_openstackcontrolplanes.yaml
  apis/bases/core.openstack.org_openstackversions.yaml
  apis/core/v1beta1/conditions.go
  apis/core/v1beta1/openstackcontrolplane_types.go
  apis/core/v1beta1/openstackcontrolplane_webhook.go
  apis/core/v1beta1/openstackversion_types.go
  apis/core/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/core.openstack.org_openstackcontrolplanes.yaml
  config/crd/bases/core.openstack.org_openstackversions.yaml
  config/manifests/bases/openstack-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/samples/core_v1beta1_openstackcontrolplane.yaml
  config/samples/core_v1beta1_openstackcontrolplane_galera.yaml
  config/samples/core_v1beta1_openstackcontrolplane_galera_3replicas.yaml
  config/samples/core_v1beta1_openstackcontrolplane_galera_network_isolation.yaml
  config/samples/core_v1beta1_openstackcontrolplane_galera_network_isolation_3replicas.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation_ceph.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation_tls_public_endpoint.yaml
  controllers/core/openstackcontrolplane_controller.go
  hack/export_related_images.sh
  main.go
  pkg/openstack/common.go
  pkg/openstack/redis.go
  pkg/openstack/version.go
  tests/functional/base_test.go
  tests/functional/openstackversion_controller_test.go
  tests/functional/suite_test.go
Labels: approved, lgtm

#754 Copy values to telemetry.autoscaling.aodh
  pkg/openstack/telemetry.go
Labels: approved, lgtm

#730 Create ONVDB client certificate for Octavia
  pkg/openstack/octavia.go
Labels: approved, lgtm

#764 Add missing default for Octavia ApacheImage
  pkg/openstack/octavia.go
Labels: approved, lgtm

#760 Add type label to osctlplane object
  apis/core/v1beta1/openstackcontrolplane_webhook.go
  tests/functional/openstackoperator_controller_test.go
Labels: approved, lgtm

#768 Restore lastTransitionTime of ReadyCondition
  controllers/core/openstackcontrolplane_controller.go
  controllers/core/openstackversion_controller.go
Labels: approved, lgtm

#769 Add sample which only has services which are enabled per default
  config/samples/core_v1beta1_openstackcontrolplane_galera_network_isolation_3replicas_only_default_enabled_services.yaml
Labels: approved, lgtm

#759 Remove networkAttachment for ovnNorthd
  config/samples/core_v1beta1_openstackcontrolplane_galera_network_isolation.yaml
  config/samples/core_v1beta1_openstackcontrolplane_galera_network_isolation_3replicas.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation_ceph.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation_tls_public_endpoint.yaml
Labels: approved, lgtm, ok-to-test

#773 Ensure golangci-lint runs on all files
  .pre-commit-config.yaml
  controllers/client/openstackclient_controller.go
  controllers/core/openstackcontrolplane_controller.go
  controllers/core/openstackversion_controller.go
  pkg/openstack/ca.go
  pkg/openstack/galera.go
  pkg/openstack/memcached.go
  pkg/openstack/nova.go
  pkg/openstack/ovn.go
  pkg/openstack/rabbitmq.go
  pkg/openstack/version.go
  pkg/openstackclient/funcs.go
  tests/functional/base_test.go
  tests/functional/openstackclient_webhook_test.go
  tests/functional/openstackoperator_controller_test.go
  tests/functional/openstackversion_controller_test.go
  tests/functional/suite_test.go
Labels: approved, lgtm

#776 [tls] fix neutron, octavia and ovn default cert duration, renwebefore
  pkg/openstack/neutron.go
  pkg/openstack/octavia.go
  pkg/openstack/ovn.go
Labels: approved, lgtm

#775 Version: Create helper before manipulating instance
  controllers/core/openstackversion_controller.go
Labels: approved, lgtm

#758 Add CeilometerProxy image
  apis/bases/core.openstack.org_openstackcontrolplanes.yaml
  apis/bases/core.openstack.org_openstackversions.yaml
  apis/core/v1beta1/openstackversion_types.go
  apis/core/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/core.openstack.org_openstackcontrolplanes.yaml
  config/crd/bases/core.openstack.org_openstackversions.yaml
  hack/export_related_images.sh
  pkg/openstack/telemetry.go
  pkg/openstack/version.go
  tests/functional/openstackversion_controller_test.go
Labels: approved, lgtm

#779 [tls] introduce dedicated CA for libvirt and update default cert durations
  apis/bases/core.openstack.org_openstackcontrolplanes.yaml
  apis/core/v1beta1/openstackcontrolplane_types.go
  apis/core/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/core.openstack.org_openstackcontrolplanes.yaml
  config/manifests/bases/openstack-operator.clusterserviceversion.yaml
  pkg/openstack/ca.go
  tests/functional/base_test.go
  tests/functional/openstackoperator_controller_test.go
  tests/kuttl/common/assert-sample-deployment.yaml
  tests/kuttl/tests/collapsed/01-assert-collapsed-cell.yaml
  tests/kuttl/tests/galera-3replicas/01-assert-galera-3replicas.yaml
  tests/kuttl/tests/galera-basic/01-assert-galera.yaml
Labels: approved, lgtm

#774 Update telemetry.autoscaling in sample CRs
  config/samples/core_v1beta1_openstackcontrolplane.yaml
  config/samples/core_v1beta1_openstackcontrolplane_collapsed_cell.yaml
  config/samples/core_v1beta1_openstackcontrolplane_galera.yaml
  config/samples/core_v1beta1_openstackcontrolplane_galera_3replicas.yaml
  config/samples/core_v1beta1_openstackcontrolplane_galera_network_isolation.yaml
  config/samples/core_v1beta1_openstackcontrolplane_galera_network_isolation_3replicas.yaml
  config/samples/core_v1beta1_openstackcontrolplane_galera_network_isolation_3replicas_only_default_enabled_services.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation_ceph.yaml
  config/samples/core_v1beta1_openstackcontrolplane_network_isolation_tls_public_endpoint.yaml
Labels: approved, lgtm

#780 [tls] nova novncproxy vencrypt support
  pkg/openstack/nova.go
Labels: approved, lgtm

#763 Add finalizer on version
  controllers/core/openstackcontrolplane_controller.go
  controllers/core/openstackversion_controller.go
  tests/functional/base_test.go
  tests/functional/openstackoperator_controller_test.go
  tests/functional/openstackversion_controller_test.go
Labels: approved, lgtm
